{% set name = "conda-libmamba-solver" %}
{% set version = "23.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/conda/conda-libmamba-solver/archive/{{ version }}.tar.gz
  sha256: 1352575324ded8935391b6545364a27b77d57d4dfbe5e85876f8d024653d12cf
  folder: src/

build:
  noarch: python
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install src/ -vv

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >=3.8
    - conda >=23.5.0
    - libmambapy >=1.4.1
    - boltons >=23.0.0

test:
  imports:
    - conda_libmamba_solver
  commands:
    - conda create -n test --dry-run scipy --solver=libmamba
    - CONDA_SOLVER=libmamba conda create -n test --dry-run scipy

about:
  home: https://github.com/conda/conda-libmamba-solver
  license: BSD-3-Clause
  license_family: BSD
  license_file: src/LICENSE
  summary: The fast mamba solver, now in conda!
  dev_url: https://github.com/conda/conda-libmamba-solver
  doc_url: https://conda.github.io/conda-libmamba-solver/

extra:
  recipe-maintainers:
    - jaimergp
    - jezdez
    - wolfv
