{% set name = "conda-libmamba-solver" %}
{% set version = "24.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/conda/conda-libmamba-solver/archive/{{ version }}.tar.gz
  sha256: a0fa12ad921063e95dc20f47b02eaa332d386b3d4cf5268d4dcdb878e98b13a3
  folder: src/

build:
  noarch: python
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install src/ -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - conda >=23.7.4
    - libmambapy >=2.0.0
    - boltons >=23.0.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - conda_libmamba_solver
  commands:
    - conda create -n test --dry-run scipy --solver=libmamba
    - CONDA_SOLVER=libmamba conda create -n test --dry-run scipy

about:
  home: https://github.com/conda/conda-libmamba-solver
  license: BSD-3-Clause
  license_family: BSD
  license_file: src/LICENSE
  summary: The fast mamba solver, now in conda!
  dev_url: https://github.com/conda/conda-libmamba-solver
  doc_url: https://conda.github.io/conda-libmamba-solver/

extra:
  recipe-maintainers:
    - jaimergp
    - jezdez
    - wolfv
