{% set name = "conda-libmamba-solver" %}
{% set version = "22.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/conda-incubator/conda-libmamba-solver/archive/{{ version }}.tar.gz  # temporary
  sha256: c5978f2820d45fc40dde71de152a4f93e7a6518341af5d5aae443a90302c56f2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - flit-core >=3.2,<4
  run:
    - python >=3.6
    - libmambapy >=0.23
    - conda >=4.13

test:
  imports:
    - conda_libmamba_solver
  commands:
    - conda create -n test --dry-run scipy --experimental-solver=libmamba
    - CONDA_EXPERIMENTAL_SOLVER=libmamba conda create -n test --dry-run scipy

about:
  home: https://github.com/conda-incubator/conda-libmamba-solver
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The fast mamba solver, now in conda!

extra:
  recipe-maintainers:
    - jaimergp
    - jezdez
    - wolfv
